version: "3.3"
services:
    app:
        build: .
        ports:
            - "8080:8080"
    database:
        image: "mysql:8"
        environment:
            - MYSQL_ROOT_PASSWORD=tiger
        ports:
             - "3306:3306"
